pipeline {
    agent any

    stages {
        stage('CI') {
            steps {

                withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                git 'https://github.com/ShroukRamadan/CICD-Pipline-with-Jenkins.git'
                sh """
                docker login -u ${USERNAME} -p ${PASSWORD}
                cd /var/jenkins_home/workspace/Deploy-nodejs-app-on-eks/Backend-App
                docker build . -f dockerfile  -t mustafa2498/nodejs-img:v1
                docker push mustafa2498/nodejs-img:v1
                """
                
                }
            }
        }

         stage('CD') {
            steps {
                sh """
                    cd /var/jenkins_home/workspace/Deploy-nodejs-app-on-eks/App-K8s
                    kubectl apply -f ns.yml
                    kubectl apply -f .
                    kubectl get all -n app-ns
                """
            }
        }
    }
}